print(True and True)
print(False and True)
print(1==1 and 2==1)
print("test" == "test")
print(1==1 or 2!=1)
print(5>>2)
print(pow(2,2))
print(bin(20))
print(True and 1==1)
print(True and 1!=1)
print("test"=="testing")
print(1!=0 and 2==1)
print(not(True and False))
print(not(1==1 and 0!=1))
print("test"==1S)